name: Build README File
'on':
    push:
        branches:
            - main
    schedule:
        -
            cron: 0 */6 * * *
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repository
                uses: actions/checkout@v1
            -
                name: Setup NodeJs 13.x
                uses: actions/setup-node@v1
                with:
                    node-version: 13.x
            -
                name: Cache dependencies and build outputs.
                uses: actions/cache@v1
                with:
                    path: node_modules
                    key: '${{ runner.os }}-js-${{ hashFiles(''package-lock.json'')}}'
            -
                name: Install dependencies
                run: npm install
            -
                name: Generate README file
                run: node index.js
            -
                name: Commit and Push new README.md to the repository
                uses: mikeal/publish-to-github-action@master
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                    BRANCH_NAME: main
    stats:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -
                uses: anmol098/waka-readme-stats@master
                with:
                    WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
                    GH_TOKEN: '${{ secrets.GH_TOKEN }}'
                    SHOW_TOTAL_CODE_TIME: "False"
                    SHOW_PROFILE_VIEWS: "False"
                    SHOW_UPDATED_DATE: "False"
                    SHOW_LOC_CHART: "False"
                    SHOW_SHORT_INFO: "False"